# Generated by Django 5.2.8 on 2025-11-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saccouser',
            name='county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='membership_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='motor_bike_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='motor_bike_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='motor_bike_registration_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='next_of_kin_first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='next_of_kin_id_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='next_of_kin_last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='stage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='stage_chairman_first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='stage_chairman_last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='stage_chairman_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='sub_county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='sub_county_chairman_first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='sub_county_chairman_last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='sub_county_chairman_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='ward',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='ward_chairman_first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='ward_chairman_last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='ward_chairman_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='saccouser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
