# Generated by Django 5.2.8 on 2025-11-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco_users', '0002_saccouser_county_saccouser_membership_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saccouser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='saccouser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='saccouser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='saccouser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='saccouser',
            name='username',
        ),
        migrations.AlterField(
            model_name='saccouser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saccouser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='saccouser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
