# Generated by Django 5.2.8 on 2025-11-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco_users', '0003_alter_saccouser_options_alter_saccouser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saccouser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='saccouser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
